# NUMPY

NumPy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with Python

## Array

An array is a data structure that stores values of same data type. In Python, this is the main difference between arrays and lists. While python lists can contain values corresponding to different data types, arrays in python can only contain values corresponding to same data type

In [2]:
## importing numpy
import numpy as np

In [3]:
# creating a list
my_lst=[1,2,3,4,5]

# creating array using list
arr = np.array(my_lst)

In [4]:
type(arr)

numpy.ndarray

In [5]:
#shape property show (number of row,number of column) as output
arr.shape

(5,)

In [6]:
arr

array([1, 2, 3, 4, 5])

In [7]:
# reshaping array
arr.reshape(2,1)

ValueError: cannot reshape array of size 5 into shape (2,1)

In [8]:
# multidimensional array
my_lst1=[1,2,3,4,5]
my_lst2=[2,3,4,5,6]
my_lst3=[3,4,5,6,7]

#creating multidimensional array from 1d array
arr1=np.array([my_lst1,my_lst2,my_lst3])

In [9]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [10]:
arr1.shape

(3, 5)

In [11]:
# converting array to different array with different dimensions
arr.reshape(5,3)

ValueError: cannot reshape array of size 5 into shape (5,3)

In [ ]:
# arr.reshape(num) where num = number of elements in 2D array 
arr1.reshape(15)

 ## INDEXING

In [12]:
#Accessing array elements
arr=np.array((1,2,3,4,5,6,7,8,9))

In [13]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
arr[3]

4

In [15]:
#indexing in 2D array
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [16]:
arr1[:,:] 
# first : is for number of rows and second : is for number of columns

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [17]:
# printing only 0 and 2 row
arr1[0:2 , :]

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6]])

In [18]:
arr1[0:,:] 

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [19]:
arr1[0:2,0:2]

array([[1, 2],
       [2, 3]])

In [20]:
arr1[1:,3:]

array([[5, 6],
       [6, 7]])

In [23]:
arr1[1:,2:4]

array([[4, 5],
       [5, 6]])

In [27]:
arr1[1:2, 1:4]

array([[3, 4, 5]])

## Inbuilt functions in Numpy for Arrrays

In [28]:
# creating array having elements from start to end-1
arr2=np.arange(0,10)

In [29]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
# # creating array having elements from start to end-1 with gap of 2
arr2=np.arange(0,10,2)

In [31]:
arr2

array([0, 2, 4, 6, 8])

In [32]:
# creating array having elements between 1 and 10-1(9) and having  20-2(18) equidistant elements between them
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [35]:
# creating array
arr2=np.array([1,2,3,4,5,6,7,8,9,10])

In [38]:
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Copy function and broadcasting

In [47]:
# from 3 index making all elements 100
arr2[3:]=100

In [48]:
arr2

array([  1,   2,   3, 100, 100, 100, 100, 100, 100, 100])

In [49]:
arr3=arr2 # both arr3 and arr2 reference to same array object 

In [50]:
arr3[3:]=500
print(arr3)

[  1   2   3 500 500 500 500 500 500 500]


In [46]:
print(arr2)

[  1   2   3 500 500 500 500 500 500 500]


In [55]:
# To solve above reference problem of array we have copy function
arr3=arr2.copy() # arr3 have copy of arr2 as pass by value(new memory)

In [56]:
print(arr2)
print(arr3)
arr3[3:]=88

[  1   2   3 500 500 500 500 500 500 500]
[  1   2   3 500 500 500 500 500 500 500]


In [57]:
print(arr3)
print(arr2)

[ 1  2  3 88 88 88 88 88 88 88]
[  1   2   3 500 500 500 500 500 500 500]


### Condition useful for data analysis

In [58]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
val=2
arr<2  # all values less then in array will show true

array([ True, False, False, False, False, False, False, False, False])

In [64]:
# all elements multiplied by true but values in original array are  not updated
arr*2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [65]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
# all elements divided by true
arr/2

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [66]:
arr%2

array([1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int32)

In [68]:
# displaying the elements which are less than val
val=6
arr[arr<val]

array([1, 2, 3, 4, 5])

In [76]:
arr=np.arange(0,10).reshape(2,5)

In [77]:
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [78]:
arr=np.arange(0,10).reshape(5,2)

In [79]:
arr

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [80]:
# Creating 1D array with only 1  n times (default data type float)
np.ones(5)

array([1., 1., 1., 1., 1.])

In [83]:
# Creating 1D array with only 1  n times ( data type = int)
np.ones(5,dtype=int)

array([1, 1, 1, 1, 1])

In [84]:
# Creating 2D array with only 1  n times ( data type = int)
np.ones((2,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [86]:
np.ones((2,5)) # default data type float

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [89]:
# Creating array with random values between 0 t0 1
np.random.rand(3,3)

array([[0.48161545, 0.52011648, 0.26690473],
       [0.49141914, 0.18585436, 0.36643803],
       [0.55390719, 0.15031855, 0.97604824]])

In [90]:
np.random.rand(3)

array([0.22232529, 0.65778636, 0.76032383])

In [93]:
np.random.rand(3,3,3)

array([[[0.37392745, 0.08052934, 0.87364653],
        [0.72111377, 0.62446076, 0.90498549],
        [0.63219143, 0.89563138, 0.30723264]],

       [[0.66257853, 0.20505245, 0.26983263],
        [0.85457949, 0.09823922, 0.89870723],
        [0.16931033, 0.98074261, 0.50472127]],

       [[0.13788711, 0.09654377, 0.40576569],
        [0.36620013, 0.88259474, 0.66567936],
        [0.50554839, 0.00919864, 0.1281347 ]]])

In [95]:
# Creating array with standard normal distribution
arr_ex=np.random.randn(4,4)

In [98]:
arr_ex

array([[ 0.02320966, -0.59308645, -0.74152293, -1.9841902 ],
       [ 0.77703438, -0.28611551,  1.93766813,  0.94109776],
       [ 2.38611371, -0.55548014, -0.50051138, -0.41759278],
       [-0.93621337,  1.63083938, -0.51031356,  0.23976542]])

In [108]:
# Creating array with n random values between range
np.random.randint(0,100,15) # 15 random values from 0 to 99

array([50, 50, 13, 21, 86, 16, 45, 82, 44, 89, 29, 43, 94, 77, 92])

In [109]:
np.random.randint(0,100,15).reshape(3,5)

array([[ 7, 81, 28, 28,  4],
       [26, 26,  0, 44, 53],
       [94, 53, 90, 50, 58]])